---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    gateway.networking.k8s.io/generator: ingress2gateway-0.4.0
  name: auth-service-ingress-auth-service-local
  namespace: auth-service
spec:
  hostnames:
    - auth-service.local
    - sous-chef-proxy.local
  parentRefs:
    - name: kong
      namespace: kong
  rules:
    - backendRefs:
        - name: auth-service
          port: 8080
      matches:
        - path:
            type: PathPrefix
            value: /api/v1/auth
status:
  parents: []
